### ISSUE TITLE
Frontend ToDo List

### ISSUE THREAD

**Issue by grcasanova** [Aleph-finance/aleph#92]
**Stake Page**
- [ ] deposit fixed / min /max using user available liquidity
- [ ] withdraw fixed / min / max
- [x] vault APY
- [ ] list all vaults with info (token symbol, liquidity, APY)

**Dashboard**
- [x] trollbox with ens reverse lookup
- [ ] list open positions (from and to token symbol, margin, leverage, profit)
- [ ] exit
- [ ] list closed positions taken from logs with pagination

**Trade**
- [ ] list all tokens available on Uniswap v3
- [ ] minimum and maximum margin checks
- [ ] automatic max leverage
- [ ] fee preview

**General**
- [ ] error handling
- [ ] Ethereum network selection
- [ ] better MetaMask / WalletConnect integration
